// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiJuy-WPM-xB1ABQ_lJKuMQMOgptafsB0',
    appId: '1:934646592022:web:02548ce4c550724ab9fb37',
    messagingSenderId: '934646592022',
    projectId: 'papa-e0656',
    authDomain: 'papa-e0656.firebaseapp.com',
    storageBucket: 'papa-e0656.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaH9nKpcM1wlLI5PwDsC_kkJeZbcB3xdM',
    appId: '1:934646592022:android:6bcc96fd05284a89b9fb37',
    messagingSenderId: '934646592022',
    projectId: 'papa-e0656',
    storageBucket: 'papa-e0656.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQvdcGABjyYESCTDkKO-_3X0Z7f2DdlOM',
    appId: '1:934646592022:ios:7cea596da700a6f0b9fb37',
    messagingSenderId: '934646592022',
    projectId: 'papa-e0656',
    storageBucket: 'papa-e0656.appspot.com',
    iosClientId: '934646592022-uliojikjgfh9j3ukd3trh1k1a7ifndjo.apps.googleusercontent.com',
    iosBundleId: 'com.example.papas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQvdcGABjyYESCTDkKO-_3X0Z7f2DdlOM',
    appId: '1:934646592022:ios:2417e0deb42e7923b9fb37',
    messagingSenderId: '934646592022',
    projectId: 'papa-e0656',
    storageBucket: 'papa-e0656.appspot.com',
    iosClientId: '934646592022-42cpcr8oe3nrjadq6rjolbpitbqe1qd6.apps.googleusercontent.com',
    iosBundleId: 'com.example.papas.RunnerTests',
  );
}
